// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Usuario struct {
	IDUsuario  string  `json:"Id_usuario"`
	Username   string  `json:"username"`
	Email      string  `json:"email"`
	Contrasena string  `json:"contrasena"`
	Nombre     string  `json:"nombre"`
	Apellido   string  `json:"apellido"`
	Telefono   *string `json:"telefono,omitempty"`
}
