package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"

	"github.com/atuning120/proyectoIntegradorSoftware/ms-producto/internal/graph"
	"github.com/atuning120/proyectoIntegradorSoftware/ms-producto/internal/graph/model"
)

// CrearCurso is the resolver for the crearCurso field.
func (r *mutationResolver) CrearCurso(ctx context.Context, input model.NewCurso) (*model.Curso, error) {
	panic(fmt.Errorf("not implemented: CrearCurso - crearCurso"))
}

// Cursos is the resolver for the cursos field.
func (r *queryResolver) Cursos(ctx context.Context) ([]*model.Curso, error) {
	panic(fmt.Errorf("not implemented: Cursos - cursos"))
}

// TopCursos is the resolver for the topCursos field.
func (r *queryResolver) TopCursos(ctx context.Context) ([]*model.Curso, error) {
	panic(fmt.Errorf("not implemented: TopCursos - topCursos"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
